/*
 * This software is provided "as is" and any expressed or implied
 * warranties, including, but not limited to, the implied warranties of
 * merchantability and fitness for a particular purpose are disclaimed.
 * ROHM shall not be liable for any direct, indirect, consequential or 
 * incidental damages arising from using or modifying this software.
 * You (customer) can modify and use this software in whole or part on
 * your own responsibility, only for the purpose of developing the software
 * for use with microcontroller manufactured by ROHM.
 *
 * @file     ML63Q25x7.h
 * @brief    CMSIS HeaderFile
 * @version  0.40
 * @date     27. June 2024
 * @note     Generated by SVDConv V3.3.39 on Thursday, 27.06.2024 17:53:41
 *           from File 'ML63Q25x7.svd',
 *           last modified on Thursday, 27.06.2024 08:53:17
 */



/** @addtogroup ROHM Co.,Ltd.
  * @{
  */


/** @addtogroup ML63Q25x7
  * @{
  */


#ifndef ML63Q25X7_H
#define ML63Q25X7_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup Configuration_of_CMSIS
  * @{
  */



/* =========================================================================================================================== */
/* ================                                Interrupt Number Definition                                ================ */
/* =========================================================================================================================== */

typedef enum {
/* =======================================  ARM Cortex-M0+ Specific Interrupt Numbers  ======================================= */
  Reset_IRQn                = -15,              /*!< -15  Reset Vector, invoked on Power up and warm reset                     */
  NonMaskableInt_IRQn       = -14,              /*!< -14  Non maskable Interrupt, cannot be stopped or preempted               */
  HardFault_IRQn            = -13,              /*!< -13  Hard Fault, all classes of Fault                                     */
  SVCall_IRQn               =  -5,              /*!< -5 System Service Call via SVC instruction                                */
  PendSV_IRQn               =  -2,              /*!< -2 Pendable request for system service                                    */
  SysTick_IRQn              =  -1,              /*!< -1 System Tick Timer                                                      */
/* =========================================  ML63Q25x7 Specific Interrupt Numbers  ========================================== */
  EXI_IRQn                  =   0,              /*!< 0  EXI                                                                    */
  TM0_IRQn                  =   1,              /*!< 1  TM0                                                                    */
  TM1_IRQn                  =   2,              /*!< 2  TM1                                                                    */
  FTM0_IRQn                 =   3,              /*!< 3  FTM0                                                                   */
  DMAC0_IRQn                =   4,              /*!< 4  DMAC0                                                                  */
  NTMS_IRQn                 =   5,              /*!< 5  NTMS                                                                   */
  SIOF1_IRQn                =   6,              /*!< 6  SIOF1                                                                  */
  MCU_IRQn                  =   7,              /*!< 7  MCU                                                                    */
  UAF1_IRQn                 =   8,              /*!< 8  UAF1                                                                   */
  TM2_IRQn                  =   9,              /*!< 9  TM2                                                                    */
  TM3_IRQn                  =  10,              /*!< 10 TM3                                                                    */
  FTM1_IRQn                 =  11,              /*!< 11 FTM1                                                                   */
  DMAC1_IRQn                =  12,              /*!< 12 DMAC1                                                                  */
  UAF3_IRQn                 =  13,              /*!< 13 UAF3                                                                   */
  SIOF0_IRQn                =  14,              /*!< 14 SIOF0                                                                  */
  I2CF0_IRQn                =  15,              /*!< 15 I2CF0                                                                  */
  UAF0_IRQn                 =  16,              /*!< 16 UAF0                                                                   */
  TM4_IRQn                  =  17,              /*!< 17 TM4                                                                    */
  TM5_IRQn                  =  18,              /*!< 18 TM5                                                                    */
  CMP_IRQn                  =  19,              /*!< 19 CMP                                                                    */
  CLK_IRQn                  =  20,              /*!< 20 CLK                                                                    */
  VLS_IRQn                  =  21,              /*!< 21 VLS                                                                    */
  SAD_IRQn                  =  22,              /*!< 22 SAD                                                                    */
  UAF2_IRQn                 =  23,              /*!< 23 UAF2                                                                   */
  AI_INT2_IRQn              =  24,              /*!< 24 AI_INT2                                                                */
  CAN0_INT0_IRQn            =  25,              /*!< 25 CAN0_INT0                                                              */
  CAN0_INT1_IRQn            =  26,              /*!< 26 CAN0_INT1                                                              */
  SAD1_IRQn                 =  27,              /*!< 27 SAD1                                                                   */
  RTC_IRQn                  =  28,              /*!< 28 RTC                                                                    */
  LTBC_IRQn                 =  29,              /*!< 29 LTBC                                                                   */
  TM1K_IRQn                 =  30,              /*!< 30 TM1K                                                                   */
  AI_INT_IRQn               =  31               /*!< 31 AI_INT                                                                 */
} IRQn_Type;



/* =========================================================================================================================== */
/* ================                           Processor and Core Peripheral Section                           ================ */
/* =========================================================================================================================== */

/* ==========================  Configuration of the ARM Cortex-M0+ Processor and Core Peripherals  =========================== */
#define __CM0PLUS_REV                 0x0001U   /*!< CM0PLUS Core Revision                                                     */
#define __NVIC_PRIO_BITS               2        /*!< Number of Bits used for Priority Levels                                   */
#define __Vendor_SysTickConfig         0        /*!< Set to 1 if different SysTick Config is used                              */
#define __VTOR_PRESENT                 0        /*!< Set to 1 if CPU supports Vector Table Offset Register                     */
#define __MPU_PRESENT                  0        /*!< MPU present                                                               */
#define __FPU_PRESENT                  0        /*!< FPU present                                                               */
#define __DSP_PRESENT                  0        /*!< DSP extension present                                                     */


/** @} */ /* End of group Configuration_of_CMSIS */

#include "core_cm0plus.h"                       /*!< ARM Cortex-M0+ processor and core peripherals                             */
#include "system_ML63Q25x7.h"                   /*!< ML63Q25x7 System                                                          */

#ifndef __IM                                    /*!< Fallback for older CMSIS versions                                         */
  #define __IM   __I
#endif
#ifndef __OM                                    /*!< Fallback for older CMSIS versions                                         */
  #define __OM   __O
#endif
#ifndef __IOM                                   /*!< Fallback for older CMSIS versions                                         */
  #define __IOM  __IO
#endif


/* =========================================================================================================================== */
/* ================                            Device Specific Peripheral Section                             ================ */
/* =========================================================================================================================== */


/** @addtogroup Device_Peripheral_peripherals
  * @{
  */



/* =========================================================================================================================== */
/* ================                                         FLASHCNT                                          ================ */
/* =========================================================================================================================== */


/**
  * @brief Flash controller (FLASHCNT)
  */

typedef struct {                                /*!< (@ 0x40000400) FLASHCNT Structure                                         */
  __IOM uint32_t  FLASHA;                       /*!< (@ 0x00000000) Flash address register                                     */
  __IOM uint32_t  FLASHD;                       /*!< (@ 0x00000004) Flash data register                                        */
  __OM  uint32_t  FLASHCON;                     /*!< (@ 0x00000008) Flash control register                                     */
  __OM  uint32_t  FLASHACP;                     /*!< (@ 0x0000000C) Flash acceptor                                             */
  __IM  uint32_t  RESERVED;
  __IOM uint32_t  FLASHSLF;                     /*!< (@ 0x00000014) Flash self register                                        */
  __IM  uint32_t  FLASHSTA;                     /*!< (@ 0x00000018) Flash status register                                      */
} FLASHCNT_Type;                                /*!< Size = 28 (0x1c)                                                          */



/* =========================================================================================================================== */
/* ================                                           RESET                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (RESET)
  */

typedef struct {                                /*!< (@ 0x40000200) RESET Structure                                            */
  __IOM uint32_t  RSTAT;                        /*!< (@ 0x00000000) Reset status register                                      */
  __IOM uint32_t  LOCKUPEN;                     /*!< (@ 0x00000004) LOCKUP reset setting register                              */
  __OM  uint32_t  CPURST;                       /*!< (@ 0x00000008) CPU reset register                                         */
  __IOM uint32_t  SRSCR;                        /*!< (@ 0x0000000C) Software reset scratch register                            */
  __IOM uint32_t  REMAPRSTEN;                   /*!< (@ 0x00000010) REMAP register reset enable register                       */
} RESET_Type;                                   /*!< Size = 20 (0x14)                                                          */



/* =========================================================================================================================== */
/* ================                                          CLKCNT                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (CLKCNT)
  */

typedef struct {                                /*!< (@ 0x40000300) CLKCNT Structure                                           */
  __IOM uint32_t  FCON01;                       /*!< (@ 0x00000000) Frequency control register 01                              */
  __IOM uint32_t  FCON23;                       /*!< (@ 0x00000004) Frequency control register 23                              */
  __IM  uint32_t  FSTAT;                        /*!< (@ 0x00000008) Frequency status register                                  */
  __IM  uint32_t  RESERVED[2];
  __IOM uint32_t  FCON67;                       /*!< (@ 0x00000014) Frequency control register 67                              */
  __IOM uint32_t  FHWUPT;                       /*!< (@ 0x00000018) Clock startup control register                             */
  __IM  uint32_t  RESERVED1;
  __IOM uint32_t  FCON89;                       /*!< (@ 0x00000020) Frequency control register 89                              */
  __IOM uint32_t  FSTAT2;                       /*!< (@ 0x00000024) Frequency status register 2                                */
  __IM  uint32_t  RESERVED2[10];
  __IOM uint32_t  SYSCANMOD;                    /*!< (@ 0x00000050) CANCLK mode register                                       */
  __IOM uint32_t  SYSNTMSMOD;                   /*!< (@ 0x00000054) NTMSCLK mode register                                      */
} CLKCNT_Type;                                  /*!< Size = 88 (0x58)                                                          */



/* =========================================================================================================================== */
/* ================                                           NINT                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief - (NINT)
  */

typedef struct {                                /*!< (@ 0x40000100) NINT Structure                                             */
  __IM  uint32_t  RESERVED;
  __IOM uint32_t  EXIST;                        /*!< (@ 0x00000004) External Interrupt status register                         */
  __IOM uint32_t  EXICON;                       /*!< (@ 0x00000008) External interrupt control register                        */
  __IOM uint32_t  EXI03SEL;                     /*!< (@ 0x0000000C) External interrupt 03 selection register                   */
  __IOM uint32_t  EXI47SEL;                     /*!< (@ 0x00000010) External interrupt 47 selection register                   */
  __IM  uint32_t  RESERVED1[3];
  __IOM uint32_t  TCKI03SEL;                    /*!< (@ 0x00000020) Timer clock input 03 selection register                    */
  __IOM uint32_t  TCKI47SEL;                    /*!< (@ 0x00000024) Timer clock input 47 selection register                    */
} NINT_Type;                                    /*!< Size = 40 (0x28)                                                          */



/* =========================================================================================================================== */
/* ================                                           DMAC                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief - (DMAC)
  */

typedef struct {                                /*!< (@ 0x47000000) DMAC Structure                                             */
  __IOM uint32_t  DMAMOD;                       /*!< (@ 0x00000000) DMA mode register                                          */
  __IM  uint32_t  DMASTA;                       /*!< (@ 0x00000004) DMA status register                                        */
  __IM  uint32_t  DMAINT;                       /*!< (@ 0x00000008) DMA end status register                                    */
} DMAC_Type;                                    /*!< Size = 12 (0xc)                                                           */



/* =========================================================================================================================== */
/* ================                                           DMAC0                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (DMAC0)
  */

typedef struct {                                /*!< (@ 0x47000100) DMAC0 Structure                                            */
  __IOM uint32_t  DMACMSK0;                     /*!< (@ 0x00000000) DMA channel mask register                                  */
  __IOM uint32_t  DMACTMOD0;                    /*!< (@ 0x00000004) DMA transfer mode register                                 */
  __IOM uint32_t  DMACSAD0;                     /*!< (@ 0x00000008) DMA transfer source address register                       */
  __IOM uint32_t  DMACDAD0;                     /*!< (@ 0x0000000C) DMA transfer destination address register                  */
  __IOM uint32_t  DMACSIZ0;                     /*!< (@ 0x00000010) DMA transfer count register                                */
  __OM  uint32_t  DMACCINT0;                    /*!< (@ 0x00000014) DMA end status clear register                              */
} DMACn_Type;                                   /*!< Size = 24 (0x18)                                                          */



/* =========================================================================================================================== */
/* ================                                           DMAC1                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (DMAC1)
  */

typedef struct {                                /*!< (@ 0x47000200) DMAC1 Structure                                            */
  __IOM uint32_t  DMACMSK1;                     /*!< (@ 0x00000000) DMA channel mask register                                  */
  __IOM uint32_t  DMACTMOD1;                    /*!< (@ 0x00000004) DMA transfer mode register                                 */
  __IOM uint32_t  DMACSAD1;                     /*!< (@ 0x00000008) DMA transfer source address register                       */
  __IOM uint32_t  DMACDAD1;                     /*!< (@ 0x0000000C) DMA transfer destination address register                  */
  __IOM uint32_t  DMACSIZ1;                     /*!< (@ 0x00000010) DMA transfer count register                                */
  __OM  uint32_t  DMACCINT1;                    /*!< (@ 0x00000014) DMA end status clear register                              */
} DMACn1_Type;                                  /*!< Size = 24 (0x18)                                                          */



/* =========================================================================================================================== */
/* ================                                           LTBC                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief - (LTBC)
  */

typedef struct {                                /*!< (@ 0x40004000) LTBC Structure                                             */
  __IOM uint32_t  LTBR;                         /*!< (@ 0x00000000) Low-speed time base counter register                       */
  __IOM uint32_t  LTBADJ;                       /*!< (@ 0x00000004) Low-speed time base counter frequency adjustment
                                                                    register                                                   */
  __IOM uint32_t  LTBINT;                       /*!< (@ 0x00000008) Low-speed time base counter interrupt select
                                                                    resister                                                   */
  __IOM uint32_t  LTBCINTST;                    /*!< (@ 0x0000000C) Low-speed time base counter interrupt status
                                                                    register                                                   */
  __IM  uint32_t  LTBRR;                        /*!< (@ 0x00000010) Low-speed time base counter for RTC register               */
} LTBC_Type;                                    /*!< Size = 20 (0x14)                                                          */



/* =========================================================================================================================== */
/* ================                                           TIMER                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (TIMER)
  */

typedef struct {                                /*!< (@ 0x40001000) TIMER Structure                                            */
  __IOM uint32_t  TM0D;                         /*!< (@ 0x00000000) Timer 0 data register                                      */
  __IOM uint32_t  TM0C;                         /*!< (@ 0x00000004) Timer 0 counter register                                   */
  __IOM uint32_t  TM0CON;                       /*!< (@ 0x00000008) Timer 0 control register                                   */
  __IM  uint32_t  RESERVED;
  __IOM uint32_t  TM1D;                         /*!< (@ 0x00000010) Timer 1 data register                                      */
  __IOM uint32_t  TM1C;                         /*!< (@ 0x00000014) Timer 1 counter register                                   */
  __IOM uint32_t  TM1CON;                       /*!< (@ 0x00000018) Timer 1 control register                                   */
  __IM  uint32_t  RESERVED1;
  __IOM uint32_t  TM2D;                         /*!< (@ 0x00000020) Timer 2 data register                                      */
  __IOM uint32_t  TM2C;                         /*!< (@ 0x00000024) Timer 2 counter register                                   */
  __IOM uint32_t  TM2CON;                       /*!< (@ 0x00000028) Timer 2 control register                                   */
  __IM  uint32_t  RESERVED2;
  __IOM uint32_t  TM3D;                         /*!< (@ 0x00000030) Timer 3 data register                                      */
  __IOM uint32_t  TM3C;                         /*!< (@ 0x00000034) Timer 3 counter register                                   */
  __IOM uint32_t  TM3CON;                       /*!< (@ 0x00000038) Timer 3 control register                                   */
  __IM  uint32_t  RESERVED3;
  __IOM uint32_t  TM4D;                         /*!< (@ 0x00000040) Timer 4 data register                                      */
  __IOM uint32_t  TM4C;                         /*!< (@ 0x00000044) Timer 4 counter register                                   */
  __IOM uint32_t  TM4CON;                       /*!< (@ 0x00000048) Timer 4 control register                                   */
  __IM  uint32_t  RESERVED4;
  __IOM uint32_t  TM5D;                         /*!< (@ 0x00000050) Timer 5 data register                                      */
  __IOM uint32_t  TM5C;                         /*!< (@ 0x00000054) Timer 5 counter register                                   */
  __IOM uint32_t  TM5CON;                       /*!< (@ 0x00000058) Timer 5 control register                                   */
  __IM  uint32_t  RESERVED5[37];
  __OM  uint32_t  TMSTR;                        /*!< (@ 0x000000F0) Timer start register                                       */
  __OM  uint32_t  TMSTP;                        /*!< (@ 0x000000F4) Timer stop register                                        */
  __IM  uint32_t  TMSTAT;                       /*!< (@ 0x000000F8) Timer status register                                      */
} TIMER_Type;                                   /*!< Size = 252 (0xfc)                                                         */



/* =========================================================================================================================== */
/* ================                                          FTIMER                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (FTIMER)
  */

typedef struct {                                /*!< (@ 0x40002000) FTIMER Structure                                           */
  __IOM uint32_t  FT0P;                         /*!< (@ 0x00000000) FTM0 period register                                       */
  __IOM uint32_t  FT0EA;                        /*!< (@ 0x00000004) FTM0 event register A                                      */
  __IOM uint32_t  FT0EB;                        /*!< (@ 0x00000008) FTM0 event register B                                      */
  __IOM uint32_t  FT0DT;                        /*!< (@ 0x0000000C) FTM0 dead time register                                    */
  __IOM uint32_t  FT0C;                         /*!< (@ 0x00000010) FTM0 counter register                                      */
  __IOM uint32_t  FT0CON0;                      /*!< (@ 0x00000014) FTM0 control register 0                                    */
  __IOM uint32_t  FT0CON1;                      /*!< (@ 0x00000018) FTM0 control register 1                                    */
  __IOM uint32_t  FT0MOD;                       /*!< (@ 0x0000001C) FTM0 mode register                                         */
  __IOM uint32_t  FT0CLK;                       /*!< (@ 0x00000020) FTM0 clock register                                        */
  __IOM uint32_t  FT0TRG;                       /*!< (@ 0x00000024) FTM0 trigger register                                      */
  __IM  uint32_t  RESERVED[2];
  __IOM uint32_t  FT0INTE;                      /*!< (@ 0x00000030) FTM0 interrupt enable register                             */
  __IM  uint32_t  FT0INTS;                      /*!< (@ 0x00000034) FTM0 interrupt status register                             */
  __OM  uint32_t  FT0INTC;                      /*!< (@ 0x00000038) FTM0 interrupt clear register                              */
  __IM  uint32_t  RESERVED1[49];
  __IOM uint32_t  FT1P;                         /*!< (@ 0x00000100) FTM1 period register                                       */
  __IOM uint32_t  FT1EA;                        /*!< (@ 0x00000104) FTM1 event register A                                      */
  __IOM uint32_t  FT1EB;                        /*!< (@ 0x00000108) FTM1 event register B                                      */
  __IOM uint32_t  FT1DT;                        /*!< (@ 0x0000010C) FTM1 dead time register                                    */
  __IOM uint32_t  FT1C;                         /*!< (@ 0x00000110) FTM1 counter register                                      */
  __IOM uint32_t  FT1CON0;                      /*!< (@ 0x00000114) FTM1 control register 0                                    */
  __IOM uint32_t  FT1CON1;                      /*!< (@ 0x00000118) FTM1 control register 1                                    */
  __IOM uint32_t  FT1MOD;                       /*!< (@ 0x0000011C) FTM1 mode register                                         */
  __IOM uint32_t  FT1CLK;                       /*!< (@ 0x00000120) FTM1 clock register                                        */
  __IOM uint32_t  FT1TRG;                       /*!< (@ 0x00000124) FTM1 trigger register                                      */
  __IM  uint32_t  RESERVED2[2];
  __IOM uint32_t  FT1INTE;                      /*!< (@ 0x00000130) FTM1 interrupt enable register                             */
  __IM  uint32_t  FT1INTS;                      /*!< (@ 0x00000134) FTM1 interrupt status register                             */
  __OM  uint32_t  FT1INTC;                      /*!< (@ 0x00000138) FTM1 interrupt clear register                              */
  __IM  uint32_t  RESERVED3[881];
  __IOM uint32_t  FTOSL0;                       /*!< (@ 0x00000F00) FTM output select register 0                               */
  __IOM uint32_t  FTOSL4;                       /*!< (@ 0x00000F04) FTM output select register 4                               */
} FTIMER_Type;                                  /*!< Size = 3848 (0xf08)                                                       */



/* =========================================================================================================================== */
/* ================                                            RTC                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief - (RTC)
  */

typedef struct {                                /*!< (@ 0x40005000) RTC Structure                                              */
  __IOM uint32_t  RTCSEC;                       /*!< (@ 0x00000000) Real time clock second register                            */
  __IOM uint32_t  RTCMIN;                       /*!< (@ 0x00000004) Real time clock minute register                            */
  __IOM uint32_t  RTCHOUR;                      /*!< (@ 0x00000008) Real time clock hour register                              */
  __IOM uint32_t  RTCWEEK;                      /*!< (@ 0x0000000C) Real time clock week register                              */
  __IOM uint32_t  RTCDAY;                       /*!< (@ 0x00000010) Real time clock day register                               */
  __IOM uint32_t  RTCMON;                       /*!< (@ 0x00000014) Real time clock month register                             */
  __IOM uint32_t  RTCYEAR;                      /*!< (@ 0x00000018) Real time clock year register                              */
  __IOM uint32_t  RTCCON;                       /*!< (@ 0x0000001C) Real time clock control register                           */
  __IOM uint32_t  AL0MIN;                       /*!< (@ 0x00000020) Real time clock alarm 0 minute register                    */
  __IOM uint32_t  AL0HOUR;                      /*!< (@ 0x00000024) Real time clock alarm 0 hour register                      */
  __IOM uint32_t  AL0WEEK;                      /*!< (@ 0x00000028) Real time clock alarm 0 week register                      */
  __IOM uint32_t  AL1MIN;                       /*!< (@ 0x0000002C) Real time clock alarm 1 minute register                    */
  __IOM uint32_t  AL1HOUR;                      /*!< (@ 0x00000030) Real time clock alarm 1 hour register                      */
  __IOM uint32_t  AL1DAY;                       /*!< (@ 0x00000034) Real time clock alarm 1 day register                       */
  __IOM uint32_t  AL1MON;                       /*!< (@ 0x00000038) Real time clock alarm 1 month register                     */
  __IM  uint32_t  RESERVED[5];
  __IM  uint32_t  RTCHMS;                       /*!< (@ 0x00000050) Real time clock hour/minute/second register                */
  __IM  uint32_t  RTCYMDW;                      /*!< (@ 0x00000054) Real time clock year/month/day/week register               */
  __IM  uint32_t  RESERVED1[2];
  __IOM uint32_t  RTCINTST;                     /*!< (@ 0x00000060) Real time clock interrupt statusregister                   */
} RTC_Type;                                     /*!< Size = 100 (0x64)                                                         */



/* =========================================================================================================================== */
/* ================                                          TIMER1K                                          ================ */
/* =========================================================================================================================== */


/**
  * @brief - (TIMER1K)
  */

typedef struct {                                /*!< (@ 0x40006000) TIMER1K Structure                                          */
  __IOM uint32_t  T1KCR;                        /*!< (@ 0x00000000) 1 kHz timer count register                                 */
  __IOM uint32_t  T1KCON;                       /*!< (@ 0x00000004) 1 kHz timer control register                               */
} TIMER1K_Type;                                 /*!< Size = 8 (0x8)                                                            */



/* =========================================================================================================================== */
/* ================                                            WDT                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief - (WDT)
  */

typedef struct {                                /*!< (@ 0x40003000) WDT Structure                                              */
  __IOM uint32_t  WDTCON;                       /*!< (@ 0x00000000) Watchdog timer control register                            */
  __IOM uint32_t  WDTMOD;                       /*!< (@ 0x00000004) Watchdog timer mode register                               */
} WDT_Type;                                     /*!< Size = 8 (0x8)                                                            */



/* =========================================================================================================================== */
/* ================                                          SSIOF0                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (SSIOF0)
  */

typedef struct {                                /*!< (@ 0x41000800) SSIOF0 Structure                                           */
  __IOM uint32_t  SF0CTRL;                      /*!< (@ 0x00000000) SIOF0 control register                                     */
  __IOM uint32_t  SF0INTC;                      /*!< (@ 0x00000004) SIOF0 interrupt control register                           */
  __IOM uint32_t  SF0TRAC;                      /*!< (@ 0x00000008) SIOF0 transfer interval control register                   */
  __IOM uint32_t  SF0BRR;                       /*!< (@ 0x0000000C) SIOF0 baud rate register                                   */
  __IM  uint32_t  SF0SRR;                       /*!< (@ 0x00000010) SIOF0 status register                                      */
  __OM  uint32_t  SF0SRC;                       /*!< (@ 0x00000014) SIOF0 status clear register                                */
  __IM  uint32_t  SF0FSR;                       /*!< (@ 0x00000018) SIOF0 FIFO status register                                 */
  __IOM uint32_t  SF0DWR;                       /*!< (@ 0x0000001C) SIOF0 write data register                                  */
  __IM  uint32_t  SF0DRR;                       /*!< (@ 0x00000020) SIOF0 read data register                                   */
} SSIOFn_Type;                                  /*!< Size = 36 (0x24)                                                          */



/* =========================================================================================================================== */
/* ================                                          SSIOF1                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (SSIOF1)
  */

typedef struct {                                /*!< (@ 0x41000900) SSIOF1 Structure                                           */
  __IOM uint32_t  SF1CTRL;                      /*!< (@ 0x00000000) SIOF1 control register                                     */
  __IOM uint32_t  SF1INTC;                      /*!< (@ 0x00000004) SIOF1 interrupt control register                           */
  __IOM uint32_t  SF1TRAC;                      /*!< (@ 0x00000008) SIOF1 transfer interval control register                   */
  __IOM uint32_t  SF1BRR;                       /*!< (@ 0x0000000C) SIOF1 baud rate register                                   */
  __IM  uint32_t  SF1SRR;                       /*!< (@ 0x00000010) SIOF1 status register                                      */
  __OM  uint32_t  SF1SRC;                       /*!< (@ 0x00000014) SIOF1 status clear register                                */
  __IM  uint32_t  SF1FSR;                       /*!< (@ 0x00000018) SIOF1 FIFO status register                                 */
  __IOM uint32_t  SF1DWR;                       /*!< (@ 0x0000001C) SIOF1 write data register                                  */
  __IM  uint32_t  SF1DRR;                       /*!< (@ 0x00000020) SIOF1 read data register                                   */
} SSIOFn1_Type;                                 /*!< Size = 36 (0x24)                                                          */



/* =========================================================================================================================== */
/* ================                                          UARTF0                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (UARTF0)
  */

typedef struct {                                /*!< (@ 0x41001800) UARTF0 Structure                                           */
  __IOM uint32_t  UAF0BUF;                      /*!< (@ 0x00000000) UARTF0 transmit/receive buffer                             */
  __IOM uint32_t  UAF0IER;                      /*!< (@ 0x00000004) UARTF0 interrupt enable register                           */
  __IM  uint32_t  UAF0IIR;                      /*!< (@ 0x00000008) UARTF0 interrupt status register                           */
  __IOM uint32_t  UAF0MOD;                      /*!< (@ 0x0000000C) UARTF0 mode register                                       */
  __IM  uint32_t  UAF0LSR;                      /*!< (@ 0x00000010) UARTF0 line status register                                */
  __IOM uint32_t  UAF0CAJ;                      /*!< (@ 0x00000014) UARTF0 clock adjustment register                           */
} UARTFn_Type;                                  /*!< Size = 24 (0x18)                                                          */



/* =========================================================================================================================== */
/* ================                                           I2CF0                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (I2CF0)
  */

typedef struct {                                /*!< (@ 0x41002800) I2CF0 Structure                                            */
  __IOM uint32_t  I2F0SAD;                      /*!< (@ 0x00000000) I2CF0 slave address register                               */
  __IOM uint32_t  I2F0CTL;                      /*!< (@ 0x00000004) I2CF0 control register                                     */
  __IOM uint32_t  I2F0SR;                       /*!< (@ 0x00000008) I2CF0 status register                                      */
  __IOM uint32_t  I2F0DR;                       /*!< (@ 0x0000000C) I2CF0 data register                                        */
  __IM  uint32_t  I2F0MON;                      /*!< (@ 0x00000010) I2CF0 bus monitor register                                 */
  __IOM uint32_t  I2F0BC;                       /*!< (@ 0x00000014) I2CF0 bus transfer rate setup counter                      */
  __IOM uint32_t  I2F0MOD;                      /*!< (@ 0x00000018) I2CF0 mode register                                        */
  __IOM uint32_t  I2F0BSV;                      /*!< (@ 0x0000001C) I2CF0 buffer mode slave address register                   */
  __IOM uint32_t  I2F0BSB;                      /*!< (@ 0x00000020) I2CF0 buffer mode sub address register                     */
  __IOM uint32_t  I2F0BFR;                      /*!< (@ 0x00000024) I2CF0 buffer mode format register                          */
  __IOM uint32_t  I2F0BCT;                      /*!< (@ 0x00000028) I2CF0 buffer mode control register                         */
  __IOM uint32_t  I2F0BMK;                      /*!< (@ 0x0000002C) I2CF0 buffer mode interrupt mask register                  */
  __IOM uint32_t  I2F0BSR;                      /*!< (@ 0x00000030) I2CF0 buffer mode status register                          */
  __IOM uint32_t  I2F0BLV;                      /*!< (@ 0x00000034) I2CF0 buffer mode level register                           */
  __IM  uint32_t  RESERVED[4];
  __IOM uint32_t  I2F0TMR;                      /*!< (@ 0x00000048) I2CF0 timer register                                       */
  __IM  uint32_t  RESERVED1;
  __IOM uint32_t  I2F0NF;                       /*!< (@ 0x00000050) I2CF0 input noise filter setting register                  */
} I2CFn_Type;                                   /*!< Size = 84 (0x54)                                                          */



/* =========================================================================================================================== */
/* ================                                           PORT2                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (PORT2)
  */

typedef struct {                                /*!< (@ 0x40010040) PORT2 Structure                                            */
  __IOM uint32_t  P2DI;                         /*!< (@ 0x00000000) -                                                          */
  __IOM uint32_t  P2DO;                         /*!< (@ 0x00000004) -                                                          */
  __IOM uint32_t  P2MOD0;                       /*!< (@ 0x00000008) -                                                          */
} PORTn_Type;                                   /*!< Size = 12 (0xc)                                                           */



/* =========================================================================================================================== */
/* ================                                           PORT3                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (PORT3)
  */

typedef struct {                                /*!< (@ 0x40010060) PORT3 Structure                                            */
  __IOM uint32_t  P3DI;                         /*!< (@ 0x00000000) -                                                          */
  __IOM uint32_t  P3DO;                         /*!< (@ 0x00000004) -                                                          */
  __IOM uint32_t  P3MOD0;                       /*!< (@ 0x00000008) -                                                          */
  __IOM uint32_t  P3MOD1;                       /*!< (@ 0x0000000C) -                                                          */
} PORTn1_Type;                                  /*!< Size = 16 (0x10)                                                          */



/* =========================================================================================================================== */
/* ================                                           PORT4                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (PORT4)
  */

typedef struct {                                /*!< (@ 0x40010080) PORT4 Structure                                            */
  __IOM uint32_t  P4DI;                         /*!< (@ 0x00000000) -                                                          */
  __IOM uint32_t  P4DO;                         /*!< (@ 0x00000004) -                                                          */
  __IOM uint32_t  P4MOD0;                       /*!< (@ 0x00000008) -                                                          */
  __IOM uint32_t  P4MOD1;                       /*!< (@ 0x0000000C) -                                                          */
} PORTn2_Type;                                  /*!< Size = 16 (0x10)                                                          */



/* =========================================================================================================================== */
/* ================                                           PORT5                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (PORT5)
  */

typedef struct {                                /*!< (@ 0x400100A0) PORT5 Structure                                            */
  __IOM uint32_t  P5DI;                         /*!< (@ 0x00000000) -                                                          */
  __IOM uint32_t  P5DO;                         /*!< (@ 0x00000004) -                                                          */
  __IOM uint32_t  P5MOD0;                       /*!< (@ 0x00000008) -                                                          */
  __IOM uint32_t  P5MOD1;                       /*!< (@ 0x0000000C) -                                                          */
} PORTn3_Type;                                  /*!< Size = 16 (0x10)                                                          */



/* =========================================================================================================================== */
/* ================                                           PORT6                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (PORT6)
  */

typedef struct {                                /*!< (@ 0x400100C0) PORT6 Structure                                            */
  __IOM uint32_t  P6DI;                         /*!< (@ 0x00000000) -                                                          */
  __IOM uint32_t  P6DO;                         /*!< (@ 0x00000004) -                                                          */
  __IOM uint32_t  P6MOD0;                       /*!< (@ 0x00000008) -                                                          */
  __IOM uint32_t  P6MOD1;                       /*!< (@ 0x0000000C) -                                                          */
} PORTn4_Type;                                  /*!< Size = 16 (0x10)                                                          */



/* =========================================================================================================================== */
/* ================                                           PORT7                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (PORT7)
  */

typedef struct {                                /*!< (@ 0x400100E0) PORT7 Structure                                            */
  __IOM uint32_t  P7DI;                         /*!< (@ 0x00000000) -                                                          */
  __IOM uint32_t  P7DO;                         /*!< (@ 0x00000004) -                                                          */
  __IOM uint32_t  P7MOD0;                       /*!< (@ 0x00000008) -                                                          */
  __IOM uint32_t  P7MOD1;                       /*!< (@ 0x0000000C) -                                                          */
} PORTn5_Type;                                  /*!< Size = 16 (0x10)                                                          */



/* =========================================================================================================================== */
/* ================                                           PORT8                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (PORT8)
  */

typedef struct {                                /*!< (@ 0x40010100) PORT8 Structure                                            */
  __IOM uint32_t  P8DI;                         /*!< (@ 0x00000000) -                                                          */
  __IOM uint32_t  P8DO;                         /*!< (@ 0x00000004) -                                                          */
  __IOM uint32_t  P8MOD0;                       /*!< (@ 0x00000008) -                                                          */
  __IOM uint32_t  P8MOD1;                       /*!< (@ 0x0000000C) -                                                          */
} PORTn6_Type;                                  /*!< Size = 16 (0x10)                                                          */



/* =========================================================================================================================== */
/* ================                                           SADC0                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (SADC0)
  */

typedef struct {                                /*!< (@ 0x42001000) SADC0 Structure                                            */
  __IOM uint32_t  SADMOD;                       /*!< (@ 0x00000000) SA-ADC Mode Register                                       */
  __IOM uint32_t  SADCON;                       /*!< (@ 0x00000004) SA-ADC Control Register                                    */
  __IOM uint32_t  SADSTM;                       /*!< (@ 0x00000008) SA-ADC Conversion Interval Register                        */
  __IM  uint32_t  RESERVED;
  __IOM uint32_t  SADIMOD;                      /*!< (@ 0x00000010) SA-ADC Interrupt Mode Register                             */
  __IOM uint32_t  SADTRG;                       /*!< (@ 0x00000014) SA-ADC Trigger Register                                    */
  __IOM uint32_t  SADEN;                        /*!< (@ 0x00000018) SA-ADC Enable Register                                     */
  __IOM uint32_t  SADLMOD;                      /*!< (@ 0x0000001C) SA-ADC Upper/Lower Limit Mode Register                     */
  __IOM uint32_t  SADUPL;                       /*!< (@ 0x00000020) SA-ADC Upper Limit Setting Register                        */
  __IOM uint32_t  SADLOL;                       /*!< (@ 0x00000024) SA-ADC Lower Limit Setting Register                        */
  __IM  uint32_t  SADULS;                       /*!< (@ 0x00000028) SA-ADC Upper/Lower Limit Status Register                   */
  __OM  uint32_t  SADULC;                       /*!< (@ 0x0000002C) SA-ADC Upper/Lower Limit Status Clear Register             */
  __IOM uint32_t  SADTMOD;                      /*!< (@ 0x00000030) SA-ADC Test Mode Register                                  */
  __IM  uint32_t  SADR;                         /*!< (@ 0x00000034) SA-ADC Result Register                                     */
  __IM  uint32_t  SADR0;                        /*!< (@ 0x00000038) SA-ADC Result Register0                                    */
  __IM  uint32_t  SADR1;                        /*!< (@ 0x0000003C) SA-ADC Result Register1                                    */
  __IM  uint32_t  SADR2;                        /*!< (@ 0x00000040) SA-ADC Result Register2                                    */
  __IM  uint32_t  SADR3;                        /*!< (@ 0x00000044) SA-ADC Result Register3                                    */
  __IM  uint32_t  SADR4;                        /*!< (@ 0x00000048) SA-ADC Result Register4                                    */
  __IM  uint32_t  SADR5;                        /*!< (@ 0x0000004C) SA-ADC Result Register5                                    */
  __IM  uint32_t  SADR6;                        /*!< (@ 0x00000050) SA-ADC Result Register6                                    */
  __IM  uint32_t  SADR7;                        /*!< (@ 0x00000054) SA-ADC Result Register7                                    */
  __IM  uint32_t  SADR8;                        /*!< (@ 0x00000058) SA-ADC Result Register8                                    */
  __IM  uint32_t  SADR9;                        /*!< (@ 0x0000005C) SA-ADC Result Register9                                    */
  __IM  uint32_t  SADR10;                       /*!< (@ 0x00000060) SA-ADC Result Register10                                   */
  __IM  uint32_t  SADR11;                       /*!< (@ 0x00000064) SA-ADC Result Register11                                   */
} SADCn_Type;                                   /*!< Size = 104 (0x68)                                                         */



/* =========================================================================================================================== */
/* ================                                            CMP                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief - (CMP)
  */

typedef struct {                                /*!< (@ 0x42002000) CMP Structure                                              */
  __IOM uint32_t  CMPCON;                       /*!< (@ 0x00000000) Analog-compalator control                                  */
  __IOM uint32_t  CMP0MOD;                      /*!< (@ 0x00000004) Analog-compalator 0 mode                                   */
  __IOM uint32_t  CMP1MOD;                      /*!< (@ 0x00000008) Analog-compalator 1 mode                                   */
  __IOM uint32_t  CMP2MOD;                      /*!< (@ 0x0000000C) Analog-compalator 2 mode                                   */
  __IM  uint32_t  RESERVED[5];
  __IOM uint32_t  CMPINTS;                      /*!< (@ 0x00000024) Analog-compalator interrupt staus                          */
} CMP_Type;                                     /*!< Size = 40 (0x28)                                                          */



/* =========================================================================================================================== */
/* ================                                            VLS                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief - (VLS)
  */

typedef struct {                                /*!< (@ 0x42000000) VLS Structure                                              */
  __IOM uint32_t  VLS0CON;                      /*!< (@ 0x00000000) -                                                          */
  __IOM uint32_t  VLS0MOD;                      /*!< (@ 0x00000004) -                                                          */
  __IOM uint32_t  VLS0LV;                       /*!< (@ 0x00000008) -                                                          */
  __IOM uint32_t  VLS0SMP;                      /*!< (@ 0x0000000C) -                                                          */
  __IM  uint32_t  VLS0STS;                      /*!< (@ 0x00000010) -                                                          */
  __OM  uint32_t  VLS0STC;                      /*!< (@ 0x00000014) "                                                          */
} VLS_Type;                                     /*!< Size = 24 (0x18)                                                          */



/* =========================================================================================================================== */
/* ================                                          LSICNT                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (LSICNT)
  */

typedef struct {                                /*!< (@ 0x40000000) LSICNT Structure                                           */
  __IM  uint32_t  IDR;                          /*!< (@ 0x00000000) Revision Register                                          */
  __IOM uint32_t  DREQSEL;                      /*!< (@ 0x00000004) DMA Request Select register                                */
  __IOM uint32_t  BRMPNCON;                     /*!< (@ 0x00000008) BRMPN Control Register                                     */
  __IM  uint32_t  UIDR;                         /*!< (@ 0x0000000C) Unique ID Register                                         */
  __IOM uint32_t  REMAPCON;                     /*!< (@ 0x00000010) Remapping Control Register                                 */
  __IOM uint32_t  REMAPBASE;                    /*!< (@ 0x00000014) Remapping Control Register                                 */
  __IM  uint32_t  RESERVED[10];
  __IOM uint32_t  FLAWAIT;                      /*!< (@ 0x00000040) Flash wait setting Register                                */
  __IOM uint32_t  SBYCON;                       /*!< (@ 0x00000044) Standby Control Register                                   */
  __IOM uint32_t  PMCON;                        /*!< (@ 0x00000048) Power Management Control Register                          */
  __IOM uint32_t  CLKCON;                       /*!< (@ 0x0000004C) Clock Control Register                                     */
  __IOM uint32_t  RSTCON;                       /*!< (@ 0x00000050) Reset Control Register                                     */
  __IOM uint32_t  AI_MEMSEL;                    /*!< (@ 0x00000054) AI ram select register                                     */
  __IOM uint32_t  AI_INTSEL;                    /*!< (@ 0x00000058) AI interrupt select register                               */
  __IOM uint32_t  MCUINTEN;                     /*!< (@ 0x0000005C) MCU interrupt enable register                              */
  __IOM uint32_t  MCUISTAT;                     /*!< (@ 0x00000060) MCU interrupt status                                       */
} LSICNT_Type;                                  /*!< Size = 100 (0x64)                                                         */



/* =========================================================================================================================== */
/* ================                                            CRC                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief - (CRC)
  */

typedef struct {                                /*!< (@ 0x44000000) CRC Structure                                              */
  __IOM uint32_t  CRCDATA;                      /*!< (@ 0x00000000) -                                                          */
  __IOM uint32_t  CRCRES;                       /*!< (@ 0x00000004) -                                                          */
  __IOM uint32_t  CRCMOD;                       /*!< (@ 0x00000008) -                                                          */
} CRC_Type;                                     /*!< Size = 12 (0xc)                                                           */



/* =========================================================================================================================== */
/* ================                                            AI                                             ================ */
/* =========================================================================================================================== */


/**
  * @brief - (AI)
  */

typedef struct {                                /*!< (@ 0x46000000) AI Structure                                               */
  __IOM uint32_t  ML_ACC_CTRL0;                 /*!< (@ 0x00000000) -                                                          */
  __IOM uint32_t  ML_ACC_CTRL1;                 /*!< (@ 0x00000004) -                                                          */
  __IOM uint32_t  ML_ACC_CTRL2;                 /*!< (@ 0x00000008) -                                                          */
  __IOM uint32_t  ML_ACC_CTRL3;                 /*!< (@ 0x0000000C) -                                                          */
  __IOM uint32_t  ML_ACC_CTRL4;                 /*!< (@ 0x00000010) -                                                          */
  __IOM uint32_t  ML_ACC_CTRL5;                 /*!< (@ 0x00000014) -                                                          */
  __IOM uint32_t  ML_ACC_CTRL6;                 /*!< (@ 0x00000018) -                                                          */
  __IOM uint32_t  ML_ACC_CTRL7;                 /*!< (@ 0x0000001C) -                                                          */
} AI_Type;                                      /*!< Size = 32 (0x20)                                                          */



/* =========================================================================================================================== */
/* ================                                           CAN0                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief CAN Controler (CAN0)
  */

typedef struct {                                /*!< (@ 0x47001000) CAN0 Structure                                             */
  __IM  uint32_t  CANCREL;                      /*!< (@ 0x00000000) Core Release Register                                      */
  __IM  uint32_t  CANENDN;                      /*!< (@ 0x00000004) Endian Register                                            */
  __IM  uint32_t  RESERVED;
  __IOM uint32_t  CANDBTP;                      /*!< (@ 0x0000000C) Data Bit Timing / Prescaler Register                       */
  __IOM uint32_t  CANTEST;                      /*!< (@ 0x00000010) Test Register                                              */
  __IOM uint32_t  CANRWD;                       /*!< (@ 0x00000014) RAM Watchdog                                               */
  __IOM uint32_t  CANCCCR;                      /*!< (@ 0x00000018) CC Control Register                                        */
  __IOM uint32_t  CANNBTP;                      /*!< (@ 0x0000001C) Nominal Bit Timing / Prescaler Register                    */
  __IOM uint32_t  CANTSCC;                      /*!< (@ 0x00000020) Timestamp Counter Configuration                            */
  __IOM uint32_t  CANTSCV;                      /*!< (@ 0x00000024) Timestamp Counter Value                                    */
  __IOM uint32_t  CANTOCC;                      /*!< (@ 0x00000028) Timeout Counter Configuration                              */
  __IOM uint32_t  CANTOCV;                      /*!< (@ 0x0000002C) Timeout Counter Value                                      */
  __IM  uint32_t  RESERVED1[4];
  __IM  uint32_t  CANECR;                       /*!< (@ 0x00000040) Error Counter Register                                     */
  __IOM uint32_t  CANPSR;                       /*!< (@ 0x00000044) Protocol Status Register                                   */
  __IOM uint32_t  CANTDCR;                      /*!< (@ 0x00000048) Transmitter Delay Comensation Register                     */
  __IM  uint32_t  RESERVED2;
  __IOM uint32_t  CANIR;                        /*!< (@ 0x00000050) Interrupt Register                                         */
  __IOM uint32_t  CANIE;                        /*!< (@ 0x00000054) Interrupt Enable                                           */
  __IOM uint32_t  CANILS;                       /*!< (@ 0x00000058) Interrupt Line Select                                      */
  __IOM uint32_t  CANILE;                       /*!< (@ 0x0000005C) Interrupt Line Enable                                      */
  __IM  uint32_t  RESERVED3[8];
  __IOM uint32_t  CANGFC;                       /*!< (@ 0x00000080) Global Filter Configuration                                */
  __IOM uint32_t  CANSIDFC;                     /*!< (@ 0x00000084) Standard ID Filter Configuration                           */
  __IOM uint32_t  CANXIDFC;                     /*!< (@ 0x00000088) Extended ID Filter Configuration                           */
  __IM  uint32_t  RESERVED4;
  __IOM uint32_t  CANXIDAM;                     /*!< (@ 0x00000090) Extended ID AND Mask                                       */
  __IM  uint32_t  CANHPMS;                      /*!< (@ 0x00000094) High Priority Message Status                               */
  __IOM uint32_t  CANNDAT1;                     /*!< (@ 0x00000098) New Data 1                                                 */
  __IOM uint32_t  CANNDAT2;                     /*!< (@ 0x0000009C) New Data 2                                                 */
  __IOM uint32_t  CANRXF0C;                     /*!< (@ 0x000000A0) Rx FIFO 0 Configuration                                    */
  __IM  uint32_t  CANRXF0S;                     /*!< (@ 0x000000A4) Rx FIFO 0 Status                                           */
  __IOM uint32_t  CANRXF0A;                     /*!< (@ 0x000000A8) Rx FIFO 0 Acknowledge                                      */
  __IOM uint32_t  CANRXBC;                      /*!< (@ 0x000000AC) Rx Buffer Configuration                                    */
  __IOM uint32_t  CANRXF1C;                     /*!< (@ 0x000000B0) Rx FIFO 1 Configuration                                    */
  __IM  uint32_t  CANRXF1S;                     /*!< (@ 0x000000B4) Rx FIFO 1 Status                                           */
  __IOM uint32_t  CANRXF1A;                     /*!< (@ 0x000000B8) Rx FIFO 1 Acknowledge                                      */
  __IOM uint32_t  CANRXESC;                     /*!< (@ 0x000000BC) Rx Buffer / FIFO Element Size Configuration                */
  __IOM uint32_t  CANTXBC;                      /*!< (@ 0x000000C0) Tx Buffer Configuration                                    */
  __IM  uint32_t  CANTXFQS;                     /*!< (@ 0x000000C4) Tx FIFO/Queue Status                                       */
  __IOM uint32_t  CANTXESC;                     /*!< (@ 0x000000C8) Tx Buffer Element Size Configuration                       */
  __IM  uint32_t  CANTXBRP;                     /*!< (@ 0x000000CC) Tx Buffer Request Pending                                  */
  __IOM uint32_t  CANTXBAR;                     /*!< (@ 0x000000D0) Tx Buffer Add Request                                      */
  __IOM uint32_t  CANTXBCR;                     /*!< (@ 0x000000D4) Tx Buffer Cancellation Request                             */
  __IM  uint32_t  CANTXBTO;                     /*!< (@ 0x000000D8) Tx Buffer Transmission Occurred                            */
  __IM  uint32_t  CANTXBCF;                     /*!< (@ 0x000000DC) Tx Buffer Cancellation Finished                            */
  __IOM uint32_t  CANTXBTIE;                    /*!< (@ 0x000000E0) Tx Buffer Transmission Interrupt Enable                    */
  __IOM uint32_t  CANTXBCIE;                    /*!< (@ 0x000000E4) Tx Buffer Cancellation Finished Interrupt Enable           */
  __IM  uint32_t  RESERVED5[2];
  __IOM uint32_t  CANTXEFC;                     /*!< (@ 0x000000F0) Tx Event FIFO Configuration                                */
  __IM  uint32_t  CANTXEFS;                     /*!< (@ 0x000000F4) Tx Event FIFO Status                                       */
  __IOM uint32_t  CANTXEFA;                     /*!< (@ 0x000000F8) Tx Event FIFO Acknowledge                                  */
} CANn_Type;                                    /*!< Size = 252 (0xfc)                                                         */



/* =========================================================================================================================== */
/* ================                                        TMR0_COMMON                                        ================ */
/* =========================================================================================================================== */


/**
  * @brief - (TMR0_COMMON)
  */

typedef struct {                                /*!< (@ 0x40008000) TMR0_COMMON Structure                                      */
  __IOM uint32_t  TMON;                         /*!< (@ 0x00000000) Timer start register                                       */
  __OM  uint32_t  TMOFF;                        /*!< (@ 0x00000004) Timer stop register                                        */
  __IM  uint32_t  RESERVED[15];
  __IOM uint32_t  TMBRK;                        /*!< (@ 0x00000044) Timer Break setting register                               */
  __IOM uint32_t  TMBE;                         /*!< (@ 0x00000048) Timer buffer control register                              */
  __IM  uint32_t  RESERVED1;
  __IOM uint32_t  TMES;                         /*!< (@ 0x00000050) Timer emergency processing start register                  */
  __IOM uint32_t  TMEE;                         /*!< (@ 0x00000054) Timer emergency processing stop register                   */
  __IM  uint32_t  RESERVED2[26];
  __IOM uint32_t  TMGMSEL;                      /*!< (@ 0x000000C0) Timer emergency stop trigger select register               */
  __IOM uint32_t  TMGMC;                        /*!< (@ 0x000000C4) Timer emergency stop trigger processing register           */
  __IOM uint32_t  TMOPT;                        /*!< (@ 0x000000C8) Timer option register                                      */
} TMR0_COMMON_Type;                             /*!< Size = 204 (0xcc)                                                         */



/* =========================================================================================================================== */
/* ================                                        TMR0_NTMS00                                        ================ */
/* =========================================================================================================================== */


/**
  * @brief - (TMR0_NTMS00)
  */

typedef struct {                                /*!< (@ 0x40008100) TMR0_NTMS00 Structure                                      */
  __IOM uint32_t  TMD;                          /*!< (@ 0x00000000) NTMS timer mode select register                            */
  __IOM uint32_t  TMCTL;                        /*!< (@ 0x00000004) NTMS timer mode control register                           */
  __IOM uint32_t  TMLEN;                        /*!< (@ 0x00000008) NTMS timer period setting register                         */
  __IM  uint32_t  RESERVED;
  __IOM uint32_t  TMTG;                         /*!< (@ 0x00000010) NTMS timer input trigger setting register                  */
  __IOM uint32_t  TMLENB;                       /*!< (@ 0x00000014) NTMS timer period setting buffer register                  */
  __IM  uint32_t  RESERVED1[2];
  __IOM uint32_t  TMTHA0;                       /*!< (@ 0x00000020) NTMS timer waveform threshold setting register
                                                                    A0                                                         */
  __IOM uint32_t  TMTHA1;                       /*!< (@ 0x00000024) NTMS timer waveform threshold setting register
                                                                    A1                                                         */
  __IOM uint32_t  TMTHB0;                       /*!< (@ 0x00000028) NTMS timer waveform threshold setting register
                                                                    B0                                                         */
  __IOM uint32_t  TMTHB1;                       /*!< (@ 0x0000002C) NTMS timer waveform threshold setting register
                                                                    B1                                                         */
  __IOM uint32_t  TMTHA0B;                      /*!< (@ 0x00000030) NTMS timer waveform threshold setting register
                                                                    A0B                                                        */
  __IOM uint32_t  TMTHA1B;                      /*!< (@ 0x00000034) NTMS timer waveform threshold setting register
                                                                    A1B                                                        */
  __IOM uint32_t  TMGM;                         /*!< (@ 0x00000038) NTMS timer emergency stop setting register                 */
  __IM  uint32_t  RESERVED2;
  __IOM uint32_t  TMIMSK;                       /*!< (@ 0x00000040) NTMS timer interrupt mask register                         */
  __IOM uint32_t  TMISTS;                       /*!< (@ 0x00000044) NTMS timer interrupt status register                       */
  __IOM uint32_t  TMISTR;                       /*!< (@ 0x00000048) NTMS timer RAW interrupt status register                   */
  __IM  uint32_t  RESERVED3;
  __IOM uint32_t  TMMON;                        /*!< (@ 0x00000050) NTMS timer count monitor register                          */
  __IM  uint32_t  RESERVED4[2];
  __IM  uint32_t  TMEST;                        /*!< (@ 0x0000005C) NTMS timer status register                                 */
  __IOM uint32_t  TMTHB0B;                      /*!< (@ 0x00000060) NTMS timer waveform threshold setting buffer
                                                                    register B0B                                               */
  __IOM uint32_t  TMTHB1B;                      /*!< (@ 0x00000064) NTMS timer waveform threshold setting buffer
                                                                    register B1B                                               */
  __IOM uint32_t  TMDBU;                        /*!< (@ 0x00000068) NTMS timer waveform dead time setting register             */
  __IOM uint32_t  TMDBD;                        /*!< (@ 0x0000006C) NTMS timer waveform dead time setting register             */
  __IOM uint32_t  TMDBUB;                       /*!< (@ 0x00000070) NTMS timer waveform dead time setting register             */
  __IOM uint32_t  TMDBDB;                       /*!< (@ 0x00000074) NTMS timer waveform dead time setting register             */
  __IOM uint32_t  TMADCT;                       /*!< (@ 0x00000078) NTMS timer AD convert control register                     */
  __IOM uint32_t  TMADA;                        /*!< (@ 0x0000007C) NTMS timer AD convert start request timing register
                                                                    A                                                          */
  __IOM uint32_t  TMADAB;                       /*!< (@ 0x00000080) NTMS timer AD convert start request timing buffer
                                                                    register A                                                 */
  __IOM uint32_t  TMADB;                        /*!< (@ 0x00000084) NTMS timer AD convert start request timing register
                                                                    B                                                          */
  __IOM uint32_t  TMADBB;                       /*!< (@ 0x00000088) NTMS timer AD convert start request timing buffer
                                                                    register B                                                 */
} TMR0_NTMSnm_Type;                             /*!< Size = 140 (0x8c)                                                         */



/* =========================================================================================================================== */
/* ================                                          CODEOP                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief - (CODEOP)
  */

typedef struct {                                /*!< (@ 0x40000480) CODEOP Structure                                           */
  __IM  uint32_t  RESERVED;
  __IM  uint32_t  CODEOP0;                      /*!< (@ 0x00000004) -                                                          */
  __IM  uint32_t  CODEOP1;                      /*!< (@ 0x00000008) -                                                          */
} CODEOP_Type;                                  /*!< Size = 12 (0xc)                                                           */


/** @} */ /* End of group Device_Peripheral_peripherals */


/* =========================================================================================================================== */
/* ================                          Device Specific Peripheral Address Map                           ================ */
/* =========================================================================================================================== */


/** @addtogroup Device_Peripheral_peripheralAddr
  * @{
  */

#define FLASHCNT_BASE               0x40000400UL
#define RESET_BASE                  0x40000200UL
#define CLKCNT_BASE                 0x40000300UL
#define NINT_BASE                   0x40000100UL
#define DMAC_BASE                   0x47000000UL
#define DMAC0_BASE                  0x47000100UL
#define DMAC1_BASE                  0x47000200UL
#define LTBC_BASE                   0x40004000UL
#define TIMER_BASE                  0x40001000UL
#define FTIMER_BASE                 0x40002000UL
#define RTC_BASE                    0x40005000UL
#define TIMER1K_BASE                0x40006000UL
#define WDT_BASE                    0x40003000UL
#define SSIOF0_BASE                 0x41000800UL
#define SSIOF1_BASE                 0x41000900UL
#define UARTF0_BASE                 0x41001800UL
#define I2CF0_BASE                  0x41002800UL
#define PORT2_BASE                  0x40010040UL
#define PORT3_BASE                  0x40010060UL
#define PORT4_BASE                  0x40010080UL
#define PORT5_BASE                  0x400100A0UL
#define PORT6_BASE                  0x400100C0UL
#define PORT7_BASE                  0x400100E0UL
#define PORT8_BASE                  0x40010100UL
#define SADC0_BASE                  0x42001000UL
#define CMP_BASE                    0x42002000UL
#define VLS_BASE                    0x42000000UL
#define LSICNT_BASE                 0x40000000UL
#define CRC_BASE                    0x44000000UL
#define AI_BASE                     0x46000000UL
#define CAN0_BASE                   0x47001000UL
#define TMR0_COMMON_BASE            0x40008000UL
#define TMR0_NTMS00_BASE            0x40008100UL
#define CODEOP_BASE                 0x40000480UL
#define UARTF1_BASE                 0x41001820UL
#define UARTF2_BASE                 0x41001840UL
#define UARTF3_BASE                 0x41001860UL
#define SADC1_BASE                  0x42001100UL
#define TMR0_NTMS01_BASE            0x40008200UL
#define TMR0_NTMS02_BASE            0x40008300UL

/** @} */ /* End of group Device_Peripheral_peripheralAddr */


/* =========================================================================================================================== */
/* ================                                  Peripheral declaration                                   ================ */
/* =========================================================================================================================== */


/** @addtogroup Device_Peripheral_declaration
  * @{
  */

#define FLASHCNT                    ((FLASHCNT_Type*)          FLASHCNT_BASE)
#define RESET                       ((RESET_Type*)             RESET_BASE)
#define CLKCNT                      ((CLKCNT_Type*)            CLKCNT_BASE)
#define NINT                        ((NINT_Type*)              NINT_BASE)
#define DMAC                        ((DMAC_Type*)              DMAC_BASE)
#define DMAC0                       ((DMACn_Type*)             DMAC0_BASE)
#define DMAC1                       ((DMACn1_Type*)            DMAC1_BASE)
#define LTBC                        ((LTBC_Type*)              LTBC_BASE)
#define TIMER                       ((TIMER_Type*)             TIMER_BASE)
#define FTIMER                      ((FTIMER_Type*)            FTIMER_BASE)
#define RTC                         ((RTC_Type*)               RTC_BASE)
#define TIMER1K                     ((TIMER1K_Type*)           TIMER1K_BASE)
#define WDT                         ((WDT_Type*)               WDT_BASE)
#define SSIOF0                      ((SSIOFn_Type*)            SSIOF0_BASE)
#define SSIOF1                      ((SSIOFn1_Type*)           SSIOF1_BASE)
#define UARTF0                      ((UARTFn_Type*)            UARTF0_BASE)
#define I2CF0                       ((I2CFn_Type*)             I2CF0_BASE)
#define PORT2                       ((PORTn_Type*)             PORT2_BASE)
#define PORT3                       ((PORTn1_Type*)            PORT3_BASE)
#define PORT4                       ((PORTn2_Type*)            PORT4_BASE)
#define PORT5                       ((PORTn3_Type*)            PORT5_BASE)
#define PORT6                       ((PORTn4_Type*)            PORT6_BASE)
#define PORT7                       ((PORTn5_Type*)            PORT7_BASE)
#define PORT8                       ((PORTn6_Type*)            PORT8_BASE)
#define SADC0                       ((SADCn_Type*)             SADC0_BASE)
#define CMP                         ((CMP_Type*)               CMP_BASE)
#define VLS                         ((VLS_Type*)               VLS_BASE)
#define LSICNT                      ((LSICNT_Type*)            LSICNT_BASE)
#define CRC                         ((CRC_Type*)               CRC_BASE)
#define AI                          ((AI_Type*)                AI_BASE)
#define CAN0                        ((CANn_Type*)              CAN0_BASE)
#define TMR0_COMMON                 ((TMR0_COMMON_Type*)       TMR0_COMMON_BASE)
#define TMR0_NTMS00                 ((TMR0_NTMSnm_Type*)       TMR0_NTMS00_BASE)
#define CODEOP                      ((CODEOP_Type*)            CODEOP_BASE)
#define UARTF1                      ((UARTFn_Type*)            UARTF1_BASE)
#define UARTF2                      ((UARTFn_Type*)            UARTF2_BASE)
#define UARTF3                      ((UARTFn_Type*)            UARTF3_BASE)
#define SADC1                       ((SADCn_Type*)             SADC1_BASE)
#define TMR0_NTMS01                 ((TMR0_NTMSnm_Type*)       TMR0_NTMS01_BASE)
#define TMR0_NTMS02                 ((TMR0_NTMSnm_Type*)       TMR0_NTMS02_BASE)

/** @} */ /* End of group Device_Peripheral_declaration */


#ifdef __cplusplus
}
#endif

#endif /* ML63Q25X7_H */


/** @} */ /* End of group ML63Q25x7 */

/** @} */ /* End of group ROHM Co.,Ltd. */
